# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe -march=native"
MAKEOPTS="-j4 -l5"
FEATURES="getbinpkg binpkg-request-signature"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
L10N="es-419 es en-US ja"

# NOTE: This stage was built with the bindist USE flag enabled
USE="dist-kernel dbus X wayland systemd vulkan \
     pulseaudio pipewire bluetooth opengl -elogind -kde -gnome -cups -qt5"
ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"
# EMERGE_DEFAULT_OPTS="--ask"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
GRUB_PLATFORMS="efi-64"
VIDEO_CARDS="intel"
